config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#landing'
  resource :launch, only: :create
  get '/config' => 'launches#xml_config'
  get '/landing', to: 'application#landing', as: 'landing'

  resources :users, only: %i[]
  resources :submissions, only: %i[]
  resources :contexts, only: %i[]
  resources :resources, only: %i[]
  resources :enrollments, only: %i[]
  resources :consumptions, only: %i[]
  resources :tool_consumers, only: %i[]
  resources :credentials, only: %i[]
  devise_for :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: enrollments
#
#  id         :bigint           not null, primary key
#  roles      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  context_id :integer
#  user_id    :integer
#

class Enrollment < ApplicationRecord
  has_one :launch, dependent: :destroy
  has_many :submissions, dependent: :destroy
  belongs_to :context
  belongs_to :user
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action enrollment, only: %i[show edit update destroy]

  # GET /enrollments
  def index
    @users = User.all
  end

  # GET /enrollments/1
  def show; end

  # GET /enrollments/new
  def new
    @user = User.new
  end

  # GET /enrollments/1/edit
  def edit; end

  # POST /enrollments
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /enrollments/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /enrollments/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def @set_enrollment
    @enrollment = Enrollment.find(params[:id])
  end

end

app/views/enrollments/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Enrollment #<%= enrollment.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Context</dt>
      <dd><%= enrollment.context_id %></dd>

      <dt>User</dt>
      <dd><%= enrollment.user_id %></dd>

      <dt>Roles</dt>
      <dd><%= enrollment.roles %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back enrollment, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_enrollment_url(enrollment), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to enrollment, method: :delete, data: { confirm: "Do you really want to delete this enrollment?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(enrollment.updated_at) %> ago
  </div>
</div>

app/views/enrollments/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Enrollment #<%= @enrollment.id %>
      </h2>

      <div class="card-body">
        <%= render "form", enrollment: @enrollment %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Enrollments

      <%= link_to new_enrollment_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Card deck example -->

<% @enrollments.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :enrollment %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Enrollments

        <%= link_to new_enrollment_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @enrollments, partial: "list_item", as: :enrollment %>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Enrollment
      </h2>

      <div class="card-body">
        <%= render "form", enrollment: @enrollment %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @enrollment, partial: "card", as: :enrollment %>
  </div>
</div>