config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#landing'
  resource :launch, only: :create
  get '/config' => 'launches#xml_config'
  get '/landing', to: 'application#landing', as: 'landing'

  resources :users, only: %i[]
  resources :submissions, only: %i[]
  resources :contexts, only: %i[]
  resources :resources, only: %i[]
  resources :enrollments, only: %i[]
  resources :consumptions, only: %i[]
  resources :tool_consumers, only: %i[]
  resources :credentials, only: %i[]
  devise_for :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Resource #<%= resource.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Id from tc</dt>
      <dd><%= resource.id_from_tc %></dd>

      <dt>Context</dt>
      <dd><%= resource.context_id %></dd>

      <dt>Title</dt>
      <dd><%= resource.title %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back resource, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_resource_url(resource), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to resource, method: :delete, data: { confirm: "Do you really want to delete this resource?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(resource.updated_at) %> ago
  </div>
</div>

app/views/resources/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Resource #<%= @resource.id %>
      </h2>

      <div class="card-body">
        <%= render "form", resource: @resource %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/resources/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Resources

      <%= link_to new_resource_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Card deck example -->

<% @resources.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :resource %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Resources

        <%= link_to new_resource_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @resources, partial: "list_item", as: :resource %>
      </div>
    </div>
  </div>
</div>

app/views/resources/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Resource
      </h2>

      <div class="card-body">
        <%= render "form", resource: @resource %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/resources/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @resource, partial: "card", as: :resource %>
  </div>
</div>