config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#landing'
  resource :launch, only: :create
  get '/config' => 'launches#xml_config'
  get '/landing', to: 'application#landing', as: 'landing'

  resources :users, only: %i[]
  resources :submissions, only: %i[]
  resources :contexts, only: %i[]
  resources :resources, only: %i[]
  resources :enrollments, only: %i[]
  resources :consumptions, only: %i[]
  resources :tool_consumers, only: %i[]
  resources :credentials, only: %i[]
  devise_for :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/consumption.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: consumptions
#
#  id               :bigint           not null, primary key
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  credential_id    :integer
#  tool_consumer_id :integer
#

class Consumption < ApplicationRecord
  belongs_to :credential
  belongs_to :tool_consumer
end

app/controllers/consumptions_controller.rb
class ConsumptionsController < ApplicationController
  before_action consumption, only: %i[show edit update destroy]

  # GET /consumptions
  def index
    @users = User.all
  end

  # GET /consumptions/1
  def show; end

  # GET /consumptions/new
  def new
    @user = User.new
  end

  # GET /consumptions/1/edit
  def edit; end

  # POST /consumptions
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /consumptions/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /consumptions/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def @set_consumption
    @consumption = Consumption.find(params[:id])
  end

end

app/views/consumptions/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Consumption #<%= consumption.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Tool consumer</dt>
      <dd><%= consumption.tool_consumer_id %></dd>

      <dt>Credential</dt>
      <dd><%= consumption.credential_id %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back consumption, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_consumption_url(consumption), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to consumption, method: :delete, data: { confirm: "Do you really want to delete this consumption?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(consumption.updated_at) %> ago
  </div>
</div>

app/views/consumptions/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Consumption #<%= @consumption.id %>
      </h2>

      <div class="card-body">
        <%= render "form", consumption: @consumption %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/consumptions/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Consumptions

      <%= link_to new_consumption_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<!-- Card deck example -->

<% @consumptions.each_slice(3) do |slice| %>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <%= render collection: slice, partial: "card", as: :consumption %>
    </div>
  </div>
</div>
<% end %>

<!-- List group example -->

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Consumptions

        <%= link_to new_consumption_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @consumptions, partial: "list_item", as: :consumption %>
      </div>
    </div>
  </div>
</div>

app/views/consumptions/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Consumption
      </h2>

      <div class="card-body">
        <%= render "form", consumption: @consumption %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/consumptions/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @consumption, partial: "card", as: :consumption %>
  </div>
</div>